spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
server:
  port: 9008
eureka:
  client:
    service-url:
      defaultZone: http://192.168.30.222:6868/eureka
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true